name: cloud_native_food_ordering_delivery_system

environment:
  sdk: '^3.7.0'

dependencies:
  flutter_lints: ^5.0.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.4
  test: ^1.25.15
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter
